import Head from "next/head";
import { useRouter } from "next/router";
import SideBar from "@/components/sidebar";
import styles from '../../styles/type-add.module.css';

// Icons
import { IoChevronBackSharp } from 'react-icons/io5';

const TypeAdd = () => {

    const router = useRouter();

    return (
        <>
            <Head>
                <title>Type-Add</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            <div className={styles.typeAddPage}>
                <div className={styles.upperPart}>
                    <IoChevronBackSharp size={20} onClick={() => router.push('/')} />
                    <label className={styles.addLabel}>Add Name</label>
                    <SideBar />
                </div>
                <div className={styles.typeName}>
                    <label className={styles.typeNameLabel}>
                        Type Name
                    </label>
                    <textarea
                        type="text"
                        name="name"
                        className={styles.typeNameField}
                    />
                </div>
                <div className={styles.typeSubmitButton}>
                    <button className={styles.button} onClick={() => router.push('/typedata')} >
                        Submit
                    </button>
                </div>
            </div>
        </>
    );
};

export default TypeAdd;