import Head from "next/head";
import { useRouter } from "next/router";
import { useState } from "react";
import SideBar from "@/components/sidebar";
import styles from '../../styles/typedata.module.css';
import { TypeData } from "@/data/typedata";

import { Modal } from "antd";

// Icons
import { IoChevronBackSharp } from 'react-icons/io5';
import { RiDeleteBin5Line } from 'react-icons/ri';
import { FiEdit } from 'react-icons/fi';

const Type = () => {

    const router = useRouter();

    const [isModalOpen, setIsModalOpen] = useState(false);
    const showModal = () => {
        setIsModalOpen(true);
    };
    const handleCancel = () => {
        setIsModalOpen(false);
    };

    return (
        <>
            <Head>
                <title>Type-Data</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            <div className={styles.typePage}>
                <div className={styles.upperPart}>
                    <IoChevronBackSharp size={20} onClick={() => router.push('/type-add')} />
                    <label className={styles.addLabel}>Type</label>
                    <SideBar />
                </div>
                <div className={styles.addButton}>
                    <button className={styles.button} onClick={() => router.push('/type-add')}>
                        Add
                    </button>
                </div>
                <div className={styles.typeDataPart}>
                    {
                        TypeData.map((item, index) => {
                            return (
                                <div className={styles.typeDataBorder} id={index}>
                                    <span className={styles.typeNameLabel}>{item.type}</span>
                                    <div className={styles.typeIconPart}>
                                        <RiDeleteBin5Line className={styles.deleteIconType} onClick={showModal} />
                                        <FiEdit size={14} className={styles.editIconType} onClick={() => router.push('/type-add')} />
                                    </div>
                                </div>
                            )
                        })
                    }
                </div>

                <Modal open={isModalOpen} closable={false} centered footer={null}>
                    <div className={styles.modalContent}>
                        <span className={styles.deleteHead}>Delete</span>
                        <span className={styles.deleteText}>Are you sure to delete?</span>
                        <div className={styles.buttonPart}>
                            <button className={styles.yesButton} onClick={handleCancel}>Yes</button>
                            <button className={styles.noButton} onClick={handleCancel}>No</button>
                        </div>
                    </div>
                </Modal>
            </div>
        </>
    );
};

export default Type;