import Head from 'next/head';
import Image from 'next/image';
import { useState } from 'react';
import { useRouter } from 'next/router'
import styles from '../styles/login.module.css';

// Phone-Number Filed
import Input from 'react-phone-number-input/input';

// image
import Logo from '../assets/logo.png'

const Login = () => {

    const router = useRouter();

    const [value, setValue] = useState()

    return (
        <>
            <Head>
                <title>Login</title>
                <meta name="description" content="Generated by create next app" />
            </Head>


            <div className={styles.bgimage}>
                <iframe id="schedulista-widget-00" src="https://www.schedulista.com/schedule/codeparkpvt?mode=widget" allowtransparency="true" frameborder="0" scrolling="no" width="100%" height="900px">
                </iframe>
                <script id="schedulista-widget-script-00" type="text/javascript" src="https://www.schedulista.com/schedule/codeparkpvt/widget.js">
                </script>
                {/* <div className={styles.imagepart}>
                    <Image
                        src={Logo}
                        alt="icon"
                        height={120}
                        width={150}
                    />
                    <label className={styles.labelname}>Login</label>
                </div>
                <div className={styles.formpart}>
                    <div className={styles.phonenumber}>
                        <label className={styles.phonelabel}>
                            Phone Number
                        </label>
                        <Input
                            international
                            country="MY"
                            withCountryCallingCode
                            value={value}
                            className={styles.phonefield}
                            onChange={setValue} />
                    </div>
                    <div className={styles.password}>
                        <label className={styles.passwordlabel}>
                            Your Password
                        </label>
                        <input
                            type="password"
                            name="password"
                            className={styles.passwordfield}
                        />
                    </div>
                    <div className={styles.loginbutton}>
                        <button className={styles.button} onClick={() => router.push('/add-admin')}>
                            Login
                        </button>
                    </div>
                    <div className={styles.regpart}>
                        <label className={styles.signin} onClick={() => router.push('/register')}>
                            SignUp
                        </label>
                        <label className={styles.forgotpass} onClick={() => router.push('/forgot-password')}>
                            Forgot Password
                        </label>
                    </div>
                </div> */}
            </div>
        </>
    )
}

export default Login;